### Alpha Vantage

https://www.alphavantage.co/documentation/

#### Pegando cotações semanais - JSON

In [ ]:
import requests

key = 'xxxxxxxxxx' #pessoal

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY_ADJUSTED&symbol=GOOG&apikey={key}'
r = requests.get(url)
data = r.json()

display(data)

{'Information': 'We have detected your API key as MGMW8YT6P76O7LCD and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}

#### Pegando cotações semanais - CSV

In [46]:
import requests
import pandas as pd
from datetime import datetime

url = f'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY_ADJUSTED&symbol=GOOG&apikey={key}&datatype=csv'
r = requests.get(url)
df = pd.read_csv(url)

display(df.head(5))

df['timestamp'] = pd.to_datetime(df['timestamp'])
display(df.info())

df['timestamp_float'] = df['timestamp'].apply(lambda x: x.timestamp())

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(df['timestamp'], df['close'], linewidth=2)
plt.xlabel('Data')
plt.ylabel('Preço de Fechamento (USD)')
plt.title(f'Histórico de Fechamento ')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

                                                   {
0      "Information": "We have detected your API ...
1                                                  }

KeyError: 'timestamp'

### Cotações

In [ ]:
from io import StringIO
acoes = ['ITUB4', 'ABEV3', 'BBAS3']

compilada = pd.DataFrame()

for acao in acoes:
    url = f'https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol={acao}.SAO&apikey={key}&datatype=csv'
    r = requests.get(url)
    tabela = pd.read_csv(StringIO(r.text))
    lista_tabelas = [compilada, tabela]
    compilada = pd.concat(lista_tabelas)
    
display(compilada)

                                                   {
0      "Information": "We have detected your API ...
1                                                  }
0      "Information": "We have detected your API ...
1                                                  }
0      "Information": "We have detected your API ...
1                                                  }

### Encontrar ativos

In [ ]:
url = f'https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=amazon&apikey={key}&datatype=csv'
r = requests.get(url)

tabela = pd.read_csv(StringIO(r.text))
display(tabela)

                                                   {
0      "Information": "We have detected your API ...
1                                                  }

### Informações de Resultado

In [ ]:
url = f'https://www.alphavantage.co/query?function=EARNINGS&symbol=AMZN&apikey={key}'
r = requests.get(url)
data = r.json()

print(data)

{'Information': 'We have detected your API key as NOBBCKX2R8M31GI9 and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}